### ISSUE TITLE
No JSON object

### ISSUE THREAD

**Issue by eonlab** [MrMitch/realdebrid-CLI#16]
Hi,
I've installed realdebrid-cli but after I enter the username and password I get this error:
 Unable to save login information: No JSON object could be decoded

What I'm doing wrong?

Thanks

**Comment by MrMitch** [comment]
Hi,
Thank you for reporting this, this is not standard behavior and that should definitely not happen. Can you tell me more about your setup? What version did you intall, did you install it from source or using `pip`, what is are you running it on?

**Comment by eonlab** [comment]
Hi,
I've installed the last version it using pip. The setup is a standard Ubuntu Server 14.04.3 
If i try to use it with different users it always gives an error.
Initially it didn't create the config file and gave this error:
Unable to save login information: [Errno 2] No such file or directory: '/home/*****/.config/rdcli-py/conf.json'
If I create a blank config file it gives this error:
Unable to save login information: No JSON object could be decoded

**Comment by MrMitch** [comment]
Did you try to run `rdcli -i` ?

**Comment by eonlab** [comment]
Yes, I've tried rdcli -i http://somehost.com/file.zip

**Comment by MrMitch** [comment]
`rdcli -i` is used to init `rdcli`, i.e. to configure it. it's not meant to download a file. Try using `rdcli -i` with *no arguments*. `rdcli` will ask your for your login informations and strore them in the config file for you.

**Comment by eonlab** [comment]
I've tried that too, it gives the same error after entering the login info.

**Comment by MrMitch** [comment]
ok, thank you for the info. I'll investigate and keep you updated.

**Comment by MrMitch** [comment]
version ![0.8.3](https://img.shields.io/pypi/v/rdcli/0.8.3.png) fixes the problem. you can upgrade using `sudo pip install rdcli -U`

**Comment by eonlab** [comment]
Ok thanks!
Now because I'm acessing from diferent locations I get this:
Login failed: Login failed: [Error 6] PIN Code required
How can I enter the PIN Code to login?

**Comment by MrMitch** [comment]
`rdcli` does not support that at the moment, i'm afraid you'll have to enter it directly on their website.
